service: docker-selenium-lambda

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      test:
        path: ./

functions:
  demo:
    timeout: 60
    memorySize: 2048
    image:
      name: test
